
import javax.swing.*;

import java.sql.*;
public class empreg extends javax.swing.JFrame {

    /** Creates new form empreg */
    public empreg() {
        initComponents();
         choice2.add("Male");choice2.add("FeMale");
           try
           {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con=DriverManager.getConnection(  "jdbc:mysql://localhost:3306/paysquare","root","");
                ResultSet rs;
                Statement stmt = con.createStatement();
                rs = stmt.executeQuery("select * from emp ");
                int chk=0;
                while(rs.next())
                {
                    choice3.add(rs.getString("id"));
                }
                rs.close();
                stmt.close();
                con.close();        
            }
            catch(Exception e)
            {
                System.out.println("Exception occured " + e);
            }
        }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        choice2 = new java.awt.Choice();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        choice3 = new java.awt.Choice();
        jButton7 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee Registration");
        setPreferredSize(new java.awt.Dimension(1080, 530));
        getContentPane().setLayout(null);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(293, 47, 80, 26);
        getContentPane().add(choice2);
        choice2.setBounds(293, 283, 80, 20);

        jLabel6.setText("Mobile");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(122, 346, 42, 16);

        jLabel5.setText("Gender");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(122, 283, 44, 16);

        jLabel8.setText("Department");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(462, 189, 74, 16);

        jLabel7.setText("Salary");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(462, 145, 37, 16);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(293, 100, 80, 26);

        jLabel1.setText("Id");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(122, 55, 12, 16);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(293, 157, 80, 26);

        jLabel2.setText("First Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(122, 98, 68, 16);

        jLabel3.setText("Middle Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(122, 157, 82, 16);

        jLabel4.setText("Last Name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(122, 217, 66, 16);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(630, 184, 90, 26);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(293, 348, 80, 26);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(630, 140, 90, 26);

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7);
        jTextField7.setBounds(293, 212, 80, 26);

        jLabel9.setText("Designation");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(460, 246, 76, 16);

        jLabel10.setText("Email");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(460, 311, 34, 16);

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField8);
        jTextField8.setBounds(630, 241, 90, 26);
        getContentPane().add(jTextField9);
        jTextField9.setBounds(630, 306, 90, 26);

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(198, 431, 75, 29);

        jLabel11.setText("Date of Birth");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(462, 73, 79, 16);
        getContentPane().add(jTextField10);
        jTextField10.setBounds(630, 68, 90, 26);

        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(320, 431, 78, 29);

        jButton3.setText("Home");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(460, 431, 81, 29);

        jButton4.setText("New");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(122, 431, 75, 29);

        jButton6.setText("Search");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(923, 68, 85, 29);

        jLabel12.setText("Staff Id");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(799, 68, 45, 16);

        jButton5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(910, 113, 81, 29);
        getContentPane().add(choice3);
        choice3.setBounds(885, 68, 40, 20);

        jButton7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton7.setText("Update");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(799, 113, 85, 29);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel13.setText("Employee Registration");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(396, 6, 260, 28);

        jLabel14.setIcon(new javax.swing.ImageIcon("/Users/Vineeth/Downloads/Webp.net-resizeimage-16.jpg")); // NOI18N
        jLabel14.setText("jLabel14");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(0, 0, 1080, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
              String id=jTextField1.getText();
              String fn=jTextField2.getText();
              String mn=jTextField3.getText();
              String ln=jTextField7.getText();
              String gender=choice2.getSelectedItem();
              String dob=jTextField10.getText();
              String m=jTextField4.getText();
              String s=jTextField5.getText();
              String de=jTextField6.getText();
              String des=jTextField8.getText();
              String e=jTextField9.getText();
              
              int len=fn.length();
              if(len<2 || mn.equals("") || m.equals("")|| e.equals("")) {
                 JOptionPane.showMessageDialog(null,"Enter Valid Name");
                } 
              else {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con=DriverManager.getConnection(  "jdbc:mysql://localhost:3306/paysquare","root","");
                Statement stmt = con.createStatement();
                PreparedStatement pstmt=con.prepareStatement("insert into emp values(?,?,?,?,?,?,?,'',?,?,?,?)");
                pstmt.setString(1,id);
                pstmt.setString(2,fn);
                pstmt.setString(3,mn);
                pstmt.setString(4,ln);
                pstmt.setString(5,gender);
                pstmt.setString(6,dob);
                pstmt.setString(7,m);
                pstmt.setString(8,s);
                pstmt.setString(9,de);
                pstmt.setString(10,des);
                pstmt.setString(11,e);
                pstmt.setString(11,e);
                
                pstmt.executeUpdate();
                
                pstmt.close();

                JOptionPane.showMessageDialog(null,"Saved Successfully");
            }
        } 
        catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
          try
       {
        Class.forName("com.mysql.jdbc.Driver");
        Connection con=DriverManager.getConnection(  "jdbc:mysql://localhost:3306/paysquare","root","");
        ResultSet rs;
        Statement stmt = con.createStatement();
        rs = stmt.executeQuery("select * from emp ");
        int chk=1;
        while(rs.next())
        {
            chk++;
        }
        rs.close();
        stmt.close();
        con.close();
        String s="";
        s=s.valueOf(chk);
        jTextField1.setText(s);   
        }
        catch(Exception e)
        {
           System.out.println("Exception occured " + e);
        }   
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                setVisible(false);
                HomePage hm=new HomePage();
                hm.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection(  "jdbc:mysql://localhost:3306/paysquare","root","");
            ResultSet rs;
            Statement stmt = con.createStatement();
            String pid=choice3.getSelectedItem();
            rs = stmt.executeQuery("select * from emp where id= "+"'"+pid+"'");
            int chk=0;
            while(rs.next()) {
                jTextField2.setText(rs.getString("fname"));
                jTextField3.setText(rs.getString("mname"));
                jTextField7.setText(rs.getString("lname"));
                jTextField4.setText(rs.getString("m"));
                jTextField10.setText(rs.getString("dob"));
                jTextField5.setText(rs.getString("salary"));
                jTextField6.setText(rs.getString("dept"));
                jTextField8.setText(rs.getString("desg"));
                jTextField9.setText(rs.getString("email"));
            }
            rs.close();
            stmt.close();
            con.close();          
        } 
        catch(Exception e) {
            System.out.println("Exception occured " + e);
        }
}//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            String pid=choice2.getSelectedItem();
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection(  "jdbc:mysql://localhost:3306/paysquare","root","");
            Statement stmt = con.createStatement();
            PreparedStatement pstmt=con.prepareStatement("delete from emp where  id="+"'"+pid+"'");
            pstmt.executeUpdate();
            pstmt.close();
           
            JOptionPane.showMessageDialog(null,"Deleted Successfully");
            } 
        catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
}//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
            String pid=choice3.getSelectedItem();
            String fn=jTextField2.getText();
            String mn=jTextField3.getText();
            String ln=jTextField7.getText();      
            String dob=jTextField10.getText();
            String m=jTextField4.getText();
            String s=jTextField5.getText();
            String de=jTextField6.getText();
            String des=jTextField8.getText();
            String e=jTextField9.getText();
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection(  "jdbc:mysql://localhost:3306/paysquare","root","");
            Statement stmt = con.createStatement();

            PreparedStatement pstmt=con.prepareStatement("update emp set fname=?,mname=?,lname=?,dob=?,m=?,salary=? ,dept=?,desg=?,email=? where  id="+"'"+pid+"'");
            pstmt.setString(1,fn);
            pstmt.setString(2,mn);
            pstmt.setString(3,ln);
            pstmt.setString(4,dob);
            pstmt.setString(5,m);
            pstmt.setString(6,s);
            pstmt.setString(7,de);
            pstmt.setString(8,des);
            pstmt.setString(9,e);

            pstmt.executeUpdate(); 
            pstmt.close();
            
            JOptionPane.showMessageDialog(null,"Updated Successfully");
            
        } 
        catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
}//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    jTextField1.setText("");
    jTextField2.setText("");
    jTextField3.setText("");
    jTextField7.setText("");
    jTextField4.setText("");
    jTextField5.setText("");
    jTextField10.setText("");   
    jTextField6.setText("");
    jTextField8.setText("");
    jTextField9.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new empreg().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Choice choice2;
    private java.awt.Choice choice3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
