
import javax.swing.*;

import java.sql.*;
public class exp extends javax.swing.JFrame {

    /** Creates new form exp */
    public exp() {
        initComponents();
        choice2.add("1");
        choice2.add("2");
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection(  "jdbc:mysql://localhost:3306/paysquare","root","");
            ResultSet rs;
            Statement stmt = con.createStatement();
            rs = stmt.executeQuery("select * from emp ");
            int chk=0;
            while(rs.next())
            {
                choice3.add(rs.getString("id"));
            }
            rs.close();
            stmt.close();
            con.close();
        }
       catch(Exception e)
       {
           System.out.println("Exception occured " + e);
       }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        choice2 = new java.awt.Choice();
        jTextField8 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        choice3 = new java.awt.Choice();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Experience Details");
        getContentPane().setLayout(null);

        jLabel4.setText("To Date");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(122, 257, 49, 16);

        jLabel9.setText("Contact No");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(477, 202, 71, 16);

        jLabel3.setText("From Date");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(122, 197, 65, 16);
        getContentPane().add(choice2);
        choice2.setBounds(288, 321, 28, 20);

        jTextField8.setText("jTextField8");
        getContentPane().add(jTextField8);
        jTextField8.setBounds(609, 197, 80, 26);

        jTextField6.setText("jTextField6");
        getContentPane().add(jTextField6);
        jTextField6.setBounds(609, 140, 80, 26);

        jTextField7.setText("jTextField7");
        getContentPane().add(jTextField7);
        jTextField7.setBounds(288, 252, 80, 26);

        jTextField5.setText("jTextField5");
        getContentPane().add(jTextField5);
        jTextField5.setBounds(609, 76, 80, 26);

        jLabel5.setText("No Of Years");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(122, 325, 75, 16);

        jLabel8.setText("Address");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(477, 145, 51, 16);

        jLabel7.setText("Company Name");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(477, 81, 99, 16);

        jTextField2.setText("jTextField2");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(288, 129, 80, 26);

        jLabel1.setText("Id");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(122, 84, 12, 16);

        jTextField3.setText("jTextField3");
        getContentPane().add(jTextField3);
        jTextField3.setBounds(288, 197, 80, 26);

        jLabel2.setText("Previous Job");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(122, 127, 77, 16);

        jButton3.setText("Home");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(419, 353, 81, 29);

        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(329, 353, 78, 29);

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(207, 353, 75, 29);
        getContentPane().add(choice3);
        choice3.setBounds(288, 79, 28, 20);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel13.setText("Employee Experience Details");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(230, 10, 332, 28);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        setVisible(false);
        HomePage hp= new HomePage();
        hp.setVisible(true);
}//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String id=choice3.getSelectedItem();
            String pj=jTextField2.getText();
            String fd=jTextField3.getText();
            String td=jTextField7.getText();
            String noy=choice2.getSelectedItem();
            
            
            String cn=jTextField5.getText();
            String a=jTextField6.getText();
            String c=jTextField8.getText();
           
            
            if(pj.equals("" )|| fd.equals("") || td.equals("")|| cn.equals("")) {
                JOptionPane.showMessageDialog(null,"Fields Cannot be empty");
            } else {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con=DriverManager.getConnection(  "jdbc:mysql://localhost:3306/paysquare","root","");
                               
                Statement stmt = con.createStatement();
                              
                PreparedStatement pstmt=con.prepareStatement("insert into exp values(?,?,?,?,?,?,?,?)");
                pstmt.setString(1,id);
                pstmt.setString(2,pj);
                pstmt.setString(3,fd);
                pstmt.setString(4,td);
                pstmt.setString(5,noy);
                pstmt.setString(6,cn);
                pstmt.setString(7,a);
                pstmt.setString(8,c);

                pstmt.executeUpdate();
 
                pstmt.close();
                                
                JOptionPane.showMessageDialog(null,"Saved Successfully");
            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    jTextField2.setText("");
    jTextField3.setText("");
    jTextField7.setText("");
    jTextField5.setText("");
    jTextField6.setText("");
    jTextField8.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new exp().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Choice choice2;
    private java.awt.Choice choice3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
