
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.io.*;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Dimension;
import java.awt.Toolkit;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font.FontFamily;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.List;
import com.itextpdf.text.ListItem;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.GrayColor;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.pdf.PdfPTable;
import java.awt.Font;
import java.net.URL;
import java.sql.Date;
import javax.swing.JFileChooser;
public class payslip extends javax.swing.JFrame {

    /**
     * Creates new form payslip
     */
    public payslip() {
        initComponents();
        
            try
       {
           
            Class.forName("com.mysql.jdbc.Driver");
Connection con=DriverManager.getConnection(  "jdbc:mysql://localhost:3306/paysquare","root","");
        ResultSet rs;
          Statement stmt = con.createStatement();
           rs = stmt.executeQuery("select * from emp ");
      
      int chk=0;
    
      while(rs.next())
      {
          
        choice3.add(rs.getString("id"));
      
      }
      rs.close();
      stmt.close();
      con.close();

           
       }
       catch(Exception e)
       {
           System.out.println("Exception occured " + e);
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        choice3 = new java.awt.Choice();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pay Slip generation");
        getContentPane().setLayout(null);
        getContentPane().add(choice3);
        choice3.setBounds(80, 30, 60, 20);

        jLabel1.setText("Id");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 30, 12, 16);

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(160, 30, 85, 29);

        jLabel2.setText("Ename");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 90, 41, 16);

        jLabel3.setText("Salary");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 240, 37, 16);

        jLabel4.setText("Deductions");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 270, 72, 16);

        jLabel5.setText("Incentives");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 300, 64, 16);

        jLabel6.setText("NetPay");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 330, 43, 16);

        jLabel7.setText("---------");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(110, 90, 170, 16);

        jLabel8.setText("---------");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(110, 240, 100, 16);

        jLabel11.setText("0.0");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(110, 330, 100, 16);

        jButton2.setText("Calculate");
        jButton2.setActionCommand("Calculate");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(290, 180, 90, 29);

        jButton3.setText("Generate PDF");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(400, 180, 127, 29);

        jLabel9.setText("Mobile");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 120, 42, 16);

        jLabel10.setText("---------");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(110, 120, 160, 16);

        jLabel12.setText("Email ID");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(20, 150, 52, 16);

        jLabel13.setText("Department");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(20, 180, 80, 16);

        jLabel14.setText("Designation");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(20, 210, 80, 16);

        jLabel15.setText("---------");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(110, 150, 140, 16);

        jLabel16.setText("---------");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(110, 180, 110, 16);

        jLabel17.setText("---------");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(110, 210, 110, 16);

        jLabel18.setText("---------");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(110, 270, 80, 16);

        jLabel19.setText("---------");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(110, 300, 90, 16);

        jLabel20.setFont(new java.awt.Font("PT Sans Caption", 0, 15)); // NOI18N
        jLabel20.setText("PAYSLIP GENERATION");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(200, 0, 250, 30);

        jLabel22.setText("Emp ID");
        jLabel22.setToolTipText("");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(20, 70, 53, 16);

        jLabel23.setText("---------");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(110, 70, 80, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 try {
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection(  "jdbc:mysql://localhost:3306/paysquare","root","");
            ResultSet rs;
            Statement stmt = con.createStatement();
            String pid=choice3.getSelectedItem();
            rs = stmt.executeQuery("select * from emp where id= "+"'"+pid+"'");
            
            int chk=0;
            
            while(rs.next()) {
                
                jLabel7.setText(rs.getString("fname"));
                jLabel10.setText(rs.getString("m"));
                jLabel15.setText(rs.getString("email"));
                jLabel16.setText(rs.getString("dept"));
                jLabel17.setText(rs.getString("desg"));
                jLabel8.setText(rs.getString("salary"));
                jLabel23.setText(rs.getString("id"));
                
            ;
//                             
               
                
                
            }
            rs.close();
            stmt.close();
            con.close();
            
            
        } catch(Exception e) {
            System.out.println("Exception occured " + e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 try {
            //String id=choice3.getSelectedItem();
            //String fn=jLabel7.getText();
            String s=jLabel8.getText();
             
           //  String n=jLabel11.getText();
             
             float sa = Float.parseFloat(s);
             float de= (float) (0.1*sa);
             float in=(float) (0.05*sa);
             float npay=sa-de+in;
//+Float.parseFloat(s)+Float.parseFloat(s);
                                  
          String np="";
          np=np.valueOf(npay);
          jLabel11.setText(np);
          
          String ded="";
          ded=ded.valueOf(de);
          jLabel18.setText(ded);
          
          String inc="";
          inc=inc.valueOf(in);
          jLabel19.setText(inc);
               
            
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
   
     Document document = new Document();
try
{
    Class.forName("com.mysql.jdbc.Driver");
                Connection con=DriverManager.getConnection(  "jdbc:mysql://localhost:3306/paysquare","root","");
    PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream("/Users/Vineeth/Desktop/Paysquare/payslips/payslip_"+jLabel7.getText()+".pdf"));
    
    document.open();
     Rectangle rect= new Rectangle(577,825,18,15); // you can resize rectangle 
     rect.enableBorderSide(1);
     rect.enableBorderSide(2);
     rect.enableBorderSide(4);
     rect.enableBorderSide(8);
     rect.setBorderColor(BaseColor.BLACK);
     rect.setBorderWidth(1);
     document.add(rect);
    
    Image image1 = Image.getInstance("/Users/Vineeth/Desktop/Paysquare/Project/paysquare/src/Images/paysquare.jpg");
    image1.setAbsolutePosition(250,723);
    image1.scaleAbsolute(100, 100);
    document.add(image1);
    
    document.add(new Paragraph("\n\n\n"));
    document.add(new Paragraph("______________________________________________________________________________"));
    document.add(new Paragraph("                                                             Employee Pay-Slip"));
    document.add(new Paragraph("______________________________________________________________________________"));
    
    document.add(new Paragraph("Employee ID                : "+jLabel23.getText()));   
    document.add(new Paragraph("Employee Name          : "+jLabel7.getText()));
    document.add(new Paragraph("Mobile                          : "+jLabel10.getText()));
    document.add(new Paragraph("Email                            : "+jLabel15.getText()));
    document.add(new Paragraph("Department                  : "+jLabel16.getText()));
    document.add(new Paragraph("Designation                  : "+jLabel17.getText()));
    document.add(new Paragraph("Salary                           : "+jLabel8.getText()));
    document.add(new Paragraph("Deductions                   : "+jLabel18.getText()));
    document.add(new Paragraph("Incentive                       : "+jLabel19.getText()));
    document.add(new Paragraph("Amount Payable           : "+jLabel11.getText()));
    document.add(new Paragraph("\n"));
    
    document.add(new Paragraph("Note:Amount will be credited to the bank details provided by you at the time of registration."));
    
    document.add(new Paragraph("______________________________________________________________________________"));
    document.add(new Paragraph("*****************************************END OF DOCUMENT****************************************"));
    document.add(new Paragraph("______________________________________________________________________________"));
       
    
    
    document.close();
    writer.close();

} catch (Exception e) {
    JOptionPane.showMessageDialog(null, e);

    } 
//catch (Exception e)
//{
  //  e.printStackTrace();
//}

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(payslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(payslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(payslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(payslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new payslip().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Choice choice3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
