
import java.sql.*;
import java.util.Vector;  
import java.util.logging.Level;  
import java.util.logging.Logger;  
import javax.swing.JOptionPane;  
import javax.swing.table.DefaultTableModel;  
import javax.swing.*;
public class SearchEmpDetails extends javax.swing.JFrame {
//String[] columnNames = {"User name", "Email", "Password", "Country"};
    JTable table;
    Connection con;
    ResultSet rs, rs1;
    Statement st, st1;
    PreparedStatement pst;
    DefaultTableModel dm;  
    /** Creates new form SearchEmpDetails */
    public SearchEmpDetails() {
        initComponents();
         try
            {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con=DriverManager.getConnection(  "jdbc:mysql://localhost:3306/paysquare","root","");
                ResultSet rs;
                Statement stmt = con.createStatement();
                rs = stmt.executeQuery("select * from emp ");
                int chk=0;
                while(rs.next())
                {
                    choice2.add(rs.getString("id"));
                }
                rs.close();
                stmt.close();
                con.close();
            }
         catch(Exception e)
            {
                System.out.println("Exception occured " + e);
            }
        }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label2 = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        choice2 = new java.awt.Choice();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Search Employee Details");
        setPreferredSize(new java.awt.Dimension(1000, 500));
        getContentPane().setLayout(null);

        label2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label2.setText("Staff Id");
        getContentPane().add(label2);
        label2.setBounds(117, 348, 44, 18);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(292, 119, 699, 318);

        jButton5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton5.setText("Home");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(448, 443, 78, 29);
        getContentPane().add(choice2);
        choice2.setBounds(117, 376, 28, 20);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Search Employee Information");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(360, 40, 339, 28);

        jButton3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton3.setText("Staff Bank Details");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(6, 294, 280, 29);

        jButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton2.setText("Experience Details");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(6, 205, 253, 29);

        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setText("Staff Information");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(6, 119, 253, 29);

        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/Vineeth/Downloads/Webp.net-resizeimage-14.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1010, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        setVisible(false);
        HomePage h1=new HomePage();
        h1.setVisible(true);        // TODO add your handling code here:
        //quit button
}//GEN-LAST:event_jButton5ActionPerformed
 private void setEmpBank() {  
     dm = new DefaultTableModel(0, 0);  
     String s[] = new String[]{"Employee ID", "Account No.", "Bank Name","Branch","IFSC"};  
     dm.setColumnIdentifiers(s);  
     jTable1.setModel(dm);  
   }  
   private void getEmpBank()throws Exception {  
     Connection con;  
       try {  
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection(  "jdbc:mysql://localhost:3306/paysquare","root","");
       
            PreparedStatement pst0 = con.prepareStatement("select * from saldetails ");  
            ResultSet rs0 = pst0.executeQuery();  
            while (rs0.next()) {  
                String bempid = rs0.getString(1);  
                String accno= rs0.getString(2);  
                String bn = rs0.getString(3);  
                String branch = rs0.getString(4);
                String ifsc= rs0.getString(5);
                
                Vector<String> vector = new Vector<String>();  
                vector.add(bempid);
                vector.add(accno);
                vector.add(bn);
                vector.add(branch);
                vector.add(ifsc);
                dm.addRow(vector);  
            }
        } 
        catch (SQLException ex) {  
       //Logger.getLogger(student.class.getName()).log(Level.SEVERE, null, ex);  
        }  
   }  
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            setEmpBank();
            getEmpBank();
        } 
        catch(Exception ex) {
            JOptionPane.showMessageDialog(null,ex);
        }
}//GEN-LAST:event_jButton3ActionPerformed
    private void setEmpExp() {  
        dm = new DefaultTableModel(0, 0);  
        String s[] = new String[]{"Emp ID", "Company Name", "Address","Designation","Company Number"};  
        dm.setColumnIdentifiers(s);  
        jTable1.setModel(dm);  
    }  
    private void getEmpExp()throws Exception {  
        Connection con;  
        try {  
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection(  "jdbc:mysql://localhost:3306/paysquare","root","");
            PreparedStatement pst0 = con.prepareStatement("select * from exp");  
            ResultSet rs0 = pst0.executeQuery();  
            while (rs0.next()) {  
                String exid = rs0.getString(1);  
                String cname= rs0.getString(6);  
                String caddress = rs0.getString(7);  
                String desg = rs0.getString(2);
                String num = rs0.getString(8);
      
                Vector<String> vector = new Vector<String>();  
                vector.add(exid);
                vector.add(cname);
                vector.add(caddress);
                vector.add(desg);
                vector.add(num);
  
                dm.addRow(vector);  
            }  
        } 
        catch (SQLException ex) {  
       //Logger.getLogger(student.class.getName()).log(Level.SEVERE, null, ex);  
        }  
   }  
   private void setTableres() {  
     dm = new DefaultTableModel(0, 0);  
     String s[] = new String[]{" ID", "Account No", "Bank Name","Branch","IFSC CODE"};  
     dm.setColumnIdentifiers(s);  
     jTable1.setModel(dm);  
   }  
private void getdatares()throws Exception {  
     Connection con;  
       try {  
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection(  "jdbc:mysql://localhost:3306/paysquare","root","");
            PreparedStatement pst0 = con.prepareStatement("select * from saldetails");  
            ResultSet rs0 = pst0.executeQuery();  
            while (rs0.next()) {  
                String bid = rs0.getString(1);  
                String bacc= rs0.getString(2);  
                String bname = rs0.getString(3);  
                String bbranch= rs0.getString(4);  
                String bifsc = rs0.getString(5);  
        
                Vector<String> vector = new Vector<String>();    
                vector.add(bid); 
                vector.add(bacc); 
                vector.add(bname); 
                vector.add(bbranch);  
                vector.add(bifsc);      
        
                  dm.addRow(vector);  
            }  
        }
        catch (SQLException ex) {  
       //Logger.getLogger(student.class.getName()).log(Level.SEVERE, null, ex);  
     }  
}  
private void setTableEmp() {  
    dm = new DefaultTableModel(0, 0);  
    String s[] = new String[]{"ID", "First_Name","Last_Name","Gender", "DOB", "Mobile", "Salary", "Designation"};  
    dm.setColumnIdentifiers(s);  
    jTable1.setModel(dm);  
   }  
private void getDataEmp()throws Exception {  
    Connection con;  
       try {  
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection(  "jdbc:mysql://localhost:3306/paysquare","root","");
            PreparedStatement pst0 = con.prepareStatement("select * from emp");  
            ResultSet rs0 = pst0.executeQuery();  
            while (rs0.next()) {  
                String id = rs0.getString(1);  
                String fn = rs0.getString(2);  
                String ln = rs0.getString(3);  
                String ge = rs0.getString(5);  
                String dob = rs0.getString(6);  
                String mob = rs0.getString(7);  
                String sal = rs0.getString(9);
                String des = rs0.getString(11);
                
                Vector<String> vector = new Vector<String>();    
                vector.add(id); 
                vector.add(fn);  
                vector.add(ln); 
                vector.add(ge);  
                vector.add(dob); 
                vector.add(mob);     
                vector.add(sal); 
                vector.add(des);  
            
                dm.addRow(vector);  
            }  
        } 
        catch (SQLException ex) {  
       //Logger.getLogger(student.class.getName()).log(Level.SEVERE, null, ex);  
        }  
}  
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            setEmpExp();
            getEmpExp();
        } 
        catch(Exception ex) {
            JOptionPane.showMessageDialog(null,ex);
        }
}//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {          
            setTableEmp();
            getDataEmp();
        } 
        catch(Exception ex) {
            JOptionPane.showMessageDialog(null,ex);
        }
}//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new SearchEmpDetails().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Choice choice2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.awt.Label label2;
    // End of variables declaration//GEN-END:variables
}
